### ISSUE TITLE
Demo continues in an infinite loop

### ISSUE THREAD

**Issue by adthoms** [mit-acl/dpgo_ros#2]
When executing:
```
roslaunch dpgo_ros dpgo_demo.launch local_initialization_method:=Odometry
```
from Section **A first demo**, the program continues in an infinite loop. Is this behavior intended? Looping appears to occur after optimized trajectories are logged to `../catkin_ws/src/dpgo_ros/logs/agent#/` for `# = {0,1,2,3,4}`

**Comment by yuluntian** [comment]
Hi @adthoms, yes, this is the intended behavior of this demo: after each optimization finishes, the program will wait a while and then do optimization again. This is motivated to reflect what often happens in practice, where we need to run optimization periodically on the latest pose graph (but for the demo, the pose graph is not evolving because we are using a fixed dataset)
